rpc_port: 18080
worker_num: 4
build_dag_each_worker: false
dag:
    is_thread_op: true
    retry: 1
    use_profile: false
op:
    bow:
        concurrency: 2
        remote_service_conf:
            client_type: brpc
            model_config: ocr_det_model
            devices: ""
