apiVersion: v1
kind: Pod
metadata:
  name: paddleserving
  labels:
    app: paddleserving
spec:
  containers:
  - name: paddleserving
    image: hub.baidubce.com/ctr/paddleserving:latest 
    workingDir: /serving
    command: ['/bin/bash']
    args: ['run.sh']
    ports: 
    - containerPort: 8010
      name: serving

---
apiVersion: v1
kind: Service
metadata:
  name: paddleserving
spec:
  ports:
    - name: serving
      port: 8010
      protocol: TCP
  selector:
    app: paddleserving
