dag:
  is_thread_op: false
  tracer:
    interval_s: 10
http_port: 18082
op:
  faster_rcnn:
    local_service_conf:
      client_type: local_predictor
      concurrency: 2
      device_type: 1
      devices: '2'
      fetch_list:
      - save_infer_model/scale_0.tmp_1
      model_config: serving_server/
rpc_port: 9998
worker_num: 20
