worker_num: 20
dag:
  is_thread_op: false
  tracer:
    interval_s: 10
http_port: 18082
rpc_port: 9998
op:
  bert:
    concurrency: 2

    local_service_conf:
      client_type: local_predictor
      device_type: 1
      devices: '2'
      fetch_list:
      model_config: bert_seq128_model/
