dag:
  is_thread_op: false
  tracer:
    interval_s: 10
http_port: 18082
op:
  bert:
    local_service_conf:
      client_type: local_predictor
      concurrency: 2
      device_type: 1
      devices: '2'
      fetch_list:
      - pooled_output
      model_config: bert_seq128_model/
rpc_port: 9998
worker_num: 20
