CC=g++
WORKROOT=../../../

MARCS=
ifeq ($(MAC),64)
LIBPATH=$(WORKROOT)lib2-64
else
LIBPATH=$(WORKROOT)lib2
endif

PUBLIC=$(WORKROOT)/public
ULLIB=$(LIBPATH)/ullib
NSHEAD=$(PUBLIC)/nshead
DICT=$(LIBPATH)/dict
MYNET=$(PUBLIC)/ns/mynet
CONFIG=$../output
CONF_SRC=$(PUBLIC)/configure
#IDL=$(PUBLIC)/idlcompiler/compiler/output
SPREG=$(PUBLIC)/spreg/output
BSL=$(LIBPATH)/bsl

INCLUDES= -I$(CONFIG)/include -I$(ULLIB)/include -I$(ULLIB)/include/comlog \
			-I$(SPREG)/include -I$(CONF_SRC) -I$(BSL)/include
CFLAGS = -fsigned-char -Wall -W -pipe -g
LDFLAGS= -L$(ULLIB)/lib -lpthread -lm -L$(CONFIG)/lib -lconfig -lullib \
			-L$(SPREG)/lib -lspreg -L$(BSL)/lib -lbsl_exception


