#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 1

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 18080
rpc_port: 9993

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False
op:
    imagenet:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 1
        client_type: brpc
        retry: 1
        timeout: 3000
        server_endpoints: ["127.0.0.1:9400"]
        client_config: "encrypt_client"
        fetch_list: ["save_infer_model/scale_0.tmp_0"]
        batch_size: 1
        auto_batching_timeout: 2000
        use_encryption_model: True
        encryption_key: "./key" 
